package com.min.seed.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.min.seed.db.bean.SearchBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SEARCH_BEAN".
*/
public class SearchBeanDao extends AbstractDao<SearchBean, Long> {

    public static final String TABLENAME = "SEARCH_BEAN";

    /**
     * Properties of entity SearchBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SearchStr = new Property(1, String.class, "searchStr", false, "SEARCH_STR");
        public final static Property Time = new Property(2, Long.class, "time", false, "TIME");
        public final static Property Userid = new Property(3, int.class, "userid", false, "USERID");
    }


    public SearchBeanDao(DaoConfig config) {
        super(config);
    }
    
    public SearchBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SEARCH_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"SEARCH_STR\" TEXT," + // 1: searchStr
                "\"TIME\" INTEGER," + // 2: time
                "\"USERID\" INTEGER NOT NULL );"); // 3: userid
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SEARCH_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SearchBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String searchStr = entity.getSearchStr();
        if (searchStr != null) {
            stmt.bindString(2, searchStr);
        }
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(3, time);
        }
        stmt.bindLong(4, entity.getUserid());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SearchBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String searchStr = entity.getSearchStr();
        if (searchStr != null) {
            stmt.bindString(2, searchStr);
        }
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(3, time);
        }
        stmt.bindLong(4, entity.getUserid());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SearchBean readEntity(Cursor cursor, int offset) {
        SearchBean entity = new SearchBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // searchStr
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // time
            cursor.getInt(offset + 3) // userid
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SearchBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSearchStr(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTime(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setUserid(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SearchBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SearchBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SearchBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
