package com.cheguo.pos.data.local.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cheguo.pos.data.model.FailReqRecord;
import com.cheguo.pos.data.model.SearchBean;

import com.cheguo.pos.data.local.db.dao.FailReqRecordDao;
import com.cheguo.pos.data.local.db.dao.SearchBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig failReqRecordDaoConfig;
    private final DaoConfig searchBeanDaoConfig;

    private final FailReqRecordDao failReqRecordDao;
    private final SearchBeanDao searchBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        failReqRecordDaoConfig = daoConfigMap.get(FailReqRecordDao.class).clone();
        failReqRecordDaoConfig.initIdentityScope(type);

        searchBeanDaoConfig = daoConfigMap.get(SearchBeanDao.class).clone();
        searchBeanDaoConfig.initIdentityScope(type);

        failReqRecordDao = new FailReqRecordDao(failReqRecordDaoConfig, this);
        searchBeanDao = new SearchBeanDao(searchBeanDaoConfig, this);

        registerDao(FailReqRecord.class, failReqRecordDao);
        registerDao(SearchBean.class, searchBeanDao);
    }
    
    public void clear() {
        failReqRecordDaoConfig.clearIdentityScope();
        searchBeanDaoConfig.clearIdentityScope();
    }

    public FailReqRecordDao getFailReqRecordDao() {
        return failReqRecordDao;
    }

    public SearchBeanDao getSearchBeanDao() {
        return searchBeanDao;
    }

}
